export const CATEGORIES = [
  { id: "all", name: "Tất cả", icon: "📦" },
  { id: "mam-muc", name: "Mắm mực", icon: "🦑" },
  { id: "mam-ruoc", name: "Mắm ruốc muối xổi", icon: "🦐" },
  { id: "mam-nhi", name: "Mắm nhỉ", icon: "🧴" },
  { id: "combo", name: "Combo", icon: "🎁" },
  { id: "khac", name: "Đặc sản Bình Định", icon: "🌾" },
];

export const PRODUCTS = [
  {
    id: 2692,
    name: "2 hũ mắm mực 500g tặng mắm cái",
    price: 170000,
    displayPrice: "170.000 đ",
    category: "Mắm mực",
    image: "https://thuoccoba.com/wp-content/uploads/2025/11/2-hu-mam-muc-1kg-tang-mam-cai.jpg",
    isBestSeller: true,
    tag: "HOT",
    rating: 4.9,
    sold: 120,
  },
  {
    id: 157,
    name: "Mắm mực hũ 500g",
    price: 85000,
    displayPrice: "85.000 đ",
    category: "Mắm mực",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-muc-hu-500g-thuoc-co-ba.jpg",
    isBestSeller: true,
    tag: "BÁN CHẠY",
    rating: 5.0,
    sold: 350,
  },
  {
    id: 532,
    name: "Mắm mực hũ 1kg",
    price: 170000,
    displayPrice: "170.000 đ",
    category: "Mắm mực",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-muc-hu-1kg.jpg",
    isBestSeller: true,
    tag: "HOT",
    rating: 4.9,
    sold: 200,
  },
  {
    id: 161,
    name: "Mắm ruốc muối xổi hũ 500g",
    price: 80000,
    displayPrice: "80.000 đ",
    category: "Mắm ruốc muối xổi",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-ruoc-muoi-xoi-hu-500g.jpg",
    isBestSeller: true,
    tag: "OCOP",
    rating: 5.0,
    sold: 400,
  },
  {
    id: 2387,
    name: "Mắm ruốc muối xổi hũ 1kg tặng 1 chai mắm cái",
    price: 169000,
    displayPrice: "169.000 đ",
    category: "Mắm ruốc muối xổi",
    image: "https://thuoccoba.com/wp-content/uploads/2025/10/mam-ruoc-muoi-xoi-hu-1kg-tang-1-chai-mam-cai-1.jpg",
    isBestSeller: false,
    rating: 4.8,
    sold: 55,
  },
  {
    id: 2389,
    name: "Mắm ruốc muối xổi hũ 1kg tặng 1 chai mắm nêm",
    price: 169000,
    displayPrice: "169.000 đ",
    category: "Mắm ruốc muối xổi",
    image: "https://thuoccoba.com/wp-content/uploads/2025/10/mam-ruoc-muoi-xoi-hu-1kg-tang-1-chai-mam-nem.jpg",
    isBestSeller: false,
    rating: 4.8,
    sold: 50,
  },
  {
    id: 2391,
    name: "Mắm ruốc muối xổi 2 hũ 500g tặng 1 chai mắm cái",
    price: 169000,
    displayPrice: "169.000 đ",
    category: "Mắm ruốc muối xổi",
    image: "https://thuoccoba.com/wp-content/uploads/2025/10/mam-ruoc-muoi-xoi-2-hu-500g-tang-1-chai-mam-cai.jpg",
    isBestSeller: false,
    rating: 4.7,
    sold: 45,
  },
  {
    id: 2393,
    name: "Mắm ruốc muối xổi 2 hũ 500g tặng 1 chai mắm nêm",
    price: 169000,
    displayPrice: "169.000 đ",
    category: "Mắm ruốc muối xổi",
    image: "https://thuoccoba.com/wp-content/uploads/2025/10/mam-ruoc-muoi-xoi-2-hu-500g-tang-1-chai-mam-nem.jpg",
    isBestSeller: false,
    rating: 4.7,
    sold: 40,
  },
  {
    id: 2544,
    name: "Nước mắm nhỉ cá cơm chai 450ml",
    price: 60000,
    displayPrice: "60.000 đ",
    category: "Mắm nhỉ",
    image: "https://thuoccoba.com/wp-content/uploads/2025/11/nuoc-mam-nhi-ca-com-chai-450ml.jpg",
    isBestSeller: true,
    tag: "HOT",
    rating: 4.9,
    sold: 180,
  },
  {
    id: 519,
    name: "Nước mắm nhỉ cá cơm chai 950ml",
    price: 150000,
    displayPrice: "150.000 đ",
    category: "Mắm nhỉ",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-nhi-chai-1-lit.jpg",
    isBestSeller: true,
    rating: 4.9,
    sold: 150,
  },
  {
    id: 520,
    name: "Thùng 10 chai nước mắm nhỉ 450ml tặng thêm 1 chai",
    price: 600000,
    displayPrice: "600.000 đ",
    category: "Mắm nhỉ",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/thung-10-chai-nuoc-mam-nhi-5kg.jpg",
    isBestSeller: false,
    rating: 4.8,
    sold: 30,
  },
  {
    id: 2541,
    name: "Thùng 5 chai nước mắm nhỉ 950ml tặng thêm 1 chai 450ml",
    price: 740000,
    displayPrice: "740.000 đ",
    category: "Mắm nhỉ",
    image: "https://thuoccoba.com/wp-content/uploads/2025/11/thung-5-chai-nuoc-mam-nhi-950ml-tang-them-1-chai-450ml.jpg",
    isBestSeller: false,
    rating: 4.8,
    sold: 25,
  },
  {
    id: 2538,
    name: "Thùng 10 chai nước mắm nhỉ 950ml tặng thêm 1 chai",
    price: 1500000,
    displayPrice: "1.500.000 đ",
    category: "Mắm nhỉ",
    image: "https://thuoccoba.com/wp-content/uploads/2025/11/thung-10-chai-nuoc-mam-nhi-950ml-tang-1-chai.jpg",
    isBestSeller: false,
    rating: 4.9,
    sold: 15,
  },
  {
    id: 158,
    name: "Mắm cái cá cơm nguyên con 380ml",
    price: 39000,
    displayPrice: "39.000 đ",
    category: "Mắm cái cá cơm",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-cai-ca-com-nguyen-con-380ml.jpg",
    isBestSeller: false,
    rating: 4.7,
    sold: 100,
  },
  {
    id: 159,
    name: "Mắm nêm cá cơm xay 500ml",
    price: 49000,
    displayPrice: "49.000 đ",
    category: "Mắm nêm",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-nem-ca-com-xay-500ml.jpg",
    isBestSeller: false,
    rating: 4.7,
    sold: 95,
  },
  {
    id: 544,
    name: "Combo 500g mắm mực, 500g mắm ruốc nguyên chất",
    price: 160000,
    displayPrice: "160.000 đ",
    category: "Combo",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/combo-500g-mam-muc-500g-mam-ruoc-nguyen-chat.jpg",
    isBestSeller: true,
    tag: "COMBO",
    rating: 4.9,
    sold: 110,
  },
  {
    id: 545,
    name: "Combo 1kg mắm ruốc, 500g mắm mực (tặng chai mắm cái 380g)",
    price: 240000,
    displayPrice: "240.000 đ",
    category: "Combo",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/combo-1kg-mam-ruoc-500g-mam-muc-tang-chai-mam-cai-380g.jpg",
    isBestSeller: true,
    tag: "COMBO",
    rating: 4.9,
    sold: 85,
  },
  {
    id: 546,
    name: "Combo 2 hũ mắm mực (tặng 1 chai mắm nêm xay)",
    price: 170000,
    displayPrice: "170.000 đ",
    category: "Combo",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/combo-2-hu-mam-muc-tang-1-chai-mam-nem-xay.jpg",
    isBestSeller: false,
    rating: 4.8,
    sold: 70,
  },
  {
    id: 548,
    name: "Combo 4 loại mắm (mắm mực, mắm cái, mắm nhĩ, mắm nêm)",
    price: 240000,
    displayPrice: "240.000 đ",
    category: "Combo",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/combo-4-loai-mam-mam-muc-mam-cai-mam-nhi-mam-nem.jpg",
    isBestSeller: true,
    tag: "COMBO",
    rating: 5.0,
    sold: 130,
  },
  {
    id: 2395,
    name: "Combo 1kg mắm ruốc, 500g mắm mực (tặng mắm nêm 500g)",
    price: 240000,
    displayPrice: "240.000 đ",
    category: "Combo",
    image: "https://thuoccoba.com/wp-content/uploads/2025/10/combo-1kg-mam-ruoc-500g-mam-muc-tang-mam-nem-500g.jpg",
    isBestSeller: false,
    rating: 4.8,
    sold: 40,
  },
  {
    id: 535,
    name: "Bột năng 1kg",
    price: 59000,
    displayPrice: "59.000 đ",
    category: "Đặc sản Bình Định",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/bot-nang-1kg-3.jpg",
    isBestSeller: false,
    rating: 4.6,
    sold: 50,
  },
  {
    id: 534,
    name: "Bún gạo khô 1kg",
    price: 70000,
    displayPrice: "70.000 đ",
    category: "Đặc sản Bình Định",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/bun-gao-kho-1kg-2.jpg",
    isBestSeller: false,
    rating: 4.6,
    sold: 45,
  },
];

export const BANNERS = [
  {
    badge: "CHUẨN CHẤT LƯỢNG",
    title: "OCOP 4 SAO & HACCP",
    highlight: "Sản phẩm OCOP 4 sao, đạt chuẩn ATVSTP, HACCP.",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-muc-hu-500g-thuoc-co-ba.jpg",
  },
  {
    badge: "ĐẶC SẢN TRUYỀN THỐNG",
    title: "MẮM NGUYÊN CHẤT LÀNG CHÀI",
    highlight: "Cam kết không chất bảo quản – Hương vị truyền thống đậm đà.",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/mam-ruoc-muoi-xoi-hu-500g.jpg",
  },
  {
    badge: "COMBO TIẾT KIỆM",
    title: "COMBO 4 LOẠI MẮM",
    highlight: "Đủ vị mắm mực, mắm cái, mắm nhỉ, mắm nêm – dùng cả tháng.",
    image: "https://thuoccoba.com/wp-content/uploads/2025/09/combo-4-loai-mam-mam-muc-mam-cai-mam-nhi-mam-nem.jpg",
  },
];